# -*- coding: utf-8 -*-
"""app1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9sOPpctz1zA8irp4I2nL5qfjipfMOPW
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import pickle
from datetime import datetime

# ---------------------------------------
# LOAD DATA
# ---------------------------------------
df = pd.read_csv("clean_coffee_sales.csv")
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
df['date'] = df['transaction_date'].dt.date

# ---------------------------------------
# LOAD MODEL
# ---------------------------------------
with open("daily_revenue_model.pkl", "rb") as f:
    model = pickle.load(f)

# ---------------------------------------
# FEATURE PREPARATION
# ---------------------------------------
def prepare_features(date_str):
    date = pd.to_datetime(date_str)
    return [[
        date.day,
        date.month,
        date.year,
        date.weekday(),
        int(date.weekday() in [5, 6])
    ]]

# ---------------------------------------
# SIDEBAR
# ---------------------------------------
st.sidebar.title("Dashboard Controls")
st.sidebar.write("This dataset contains 149k+ coffee shop sales from 3 store locations.")

store_filter = st.sidebar.selectbox(
    "Select Store",
    ["All"] + sorted(df["store_location"].unique())
)

category_filter = st.sidebar.multiselect(
    "Select Product Category",
    sorted(df["product_category"].unique())
)

date_range = st.sidebar.date_input(
    "Select Date Range",
    value=(df["transaction_date"].min(), df["transaction_date"].max())
)

st.sidebar.markdown("---")
st.sidebar.header("Predict Daily Revenue")

pred_input = st.sidebar.date_input("Pick a Date to Predict")

if st.sidebar.button("Predict Revenue"):
    features = prepare_features(str(pred_input))
    prediction = model.predict(features)[0]
    st.sidebar.success(f"Predicted Revenue: ${prediction:,.2f}")

# ---------------------------------------
# FILTER DATA
# ---------------------------------------
filtered_df = df.copy()

if store_filter != "All":
    filtered_df = filtered_df[filtered_df["store_location"] == store_filter]

if category_filter:
    filtered_df = filtered_df[filtered_df["product_category"].isin(category_filter)]

start_date, end_date = date_range
filtered_df = filtered_df[
    (filtered_df["transaction_date"] >= pd.to_datetime(start_date)) &
    (filtered_df["transaction_date"] <= pd.to_datetime(end_date))
]

# ---------------------------------------
# MAIN PAGE
# ---------------------------------------
st.title("Coffee Shop Sales Dashboard")

# SUMMARY STATISTICS
st.subheader("Summary Statistics")
st.dataframe(filtered_df.describe())

# ---------------------------------------
# INTERACTIVE VISUALS
# ---------------------------------------
st.subheader("Interactive Visualizations")

# 1️⃣ PRODUCT CATEGORY COUNTS
if not filtered_df.empty:
    category_counts = (
        filtered_df["product_category"]
        .value_counts()
        .reset_index()
    )
    category_counts.columns = ["product_category", "count"]

    fig1 = px.bar(
        category_counts,
        x="product_category",
        y="count",
        title="Product Category Distribution",
        color="product_category"
    )
    st.plotly_chart(fig1)
else:
    st.warning("No data available for selected filters.")

# 2️⃣ SALES PER STORE
store_counts = filtered_df["store_location"].value_counts().reset_index()
store_counts.columns = ["store_location", "count"]

fig2 = px.bar(
    store_counts,
    x="store_location",
    y="count",
    title="Sales Count by Store"
)
st.plotly_chart(fig2)

# 3️⃣ DAILY REVENUE OVER TIME
daily_rev = (
    filtered_df.groupby("date")["total_price"]
    .sum()
    .reset_index()
)

fig3 = px.line(
    daily_rev,
    x="date",
    y="total_price",
    title="Daily Revenue Over Time"
)
st.plotly_chart(fig3)
# -----------------------------
# Insights Section
# -----------------------------
st.subheader("📊 Key Insights")

st.markdown("""
### 🔹 **Top Insights from the Sales Data**

#### **1️ Product Performance**
- Coffee products dominate sales, contributing the highest number of transactions and revenue.
- Tea is the second most popular category, making up a large portion of sales volume.
- Low-performing categories include **Flavours**, **Loose Tea**, and **Packaged Chocolate**.

---

#### **2️ Store-Level Insights**
- **Hell’s Kitchen** and **Astoria** generate nearly equal sales volumes.
- **Lower Manhattan** shows slightly lower sales but still stable across the date range.

---

#### **3 Customer Behavior Insights**
- Peak transactions occur between **7 AM – 11 AM**, matching typical coffee shop rush hours.
- Afternoon transactions slow down significantly after 3 PM.

---


### ✅ **Overall Conclusion**
The business is stable with strong morning demand and clear best-selling categories.  
Coffee and Tea should remain the primary focus, while low-selling items could be bundled or promoted to improve performance.
""")
